#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libmemcached
Version  : 1.0.18
Release  : 8
URL      : http://pkgs.fedoraproject.org/repo/pkgs/libmemcached/libmemcached-1.0.18-exhsieh.tar.gz/b4cd7ccfa1bca8b2563300342b9fd01f/libmemcached-1.0.18-exhsieh.tar.gz
Source0  : http://pkgs.fedoraproject.org/repo/pkgs/libmemcached/libmemcached-1.0.18-exhsieh.tar.gz/b4cd7ccfa1bca8b2563300342b9fd01f/libmemcached-1.0.18-exhsieh.tar.gz
Summary  : memcached C library and command line tools
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libmemcached-bin
Requires: libmemcached-lib
Requires: libmemcached-doc
BuildRequires : bison
BuildRequires : flex
BuildRequires : mariadb-dev
BuildRequires : pkgconfig(uuid)
BuildRequires : sed
BuildRequires : valgrind

%description
libmemcached, http://libmemcached.org/, is a C client library to the memcached server
(http://danga.com/memcached). It has been designed to be light on memory
usage, and provide full access to server side methods.

It also implements several command line tools:

memcat - Copy the value of a key to standard output.
memflush - Flush the contents of your servers.
memrm - Remove a key(s) from the serrver.
memstat - Dump the stats of your servers to standard output.
memslap - Generate testing loads on a memcached cluster.
memcp - Copy files to memcached servers.
memerror - Creates human readable messages from libmemecached error codes.
memcapable - Verify a memcached server for protocol behavior.
memexist - Check for the existance of a key.
memtouch - Update the expiration value of a key.

%package bin
Summary: bin components for the libmemcached package.
Group: Binaries

%description bin
bin components for the libmemcached package.


%package dev
Summary: dev components for the libmemcached package.
Group: Development
Requires: libmemcached-lib
Requires: libmemcached-bin

%description dev
dev components for the libmemcached package.


%package doc
Summary: doc components for the libmemcached package.
Group: Documentation

%description doc
doc components for the libmemcached package.


%package lib
Summary: lib components for the libmemcached package.
Group: Libraries

%description lib
lib components for the libmemcached package.


%prep
%setup -q -n libmemcached-1.0.18

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/memcapable
/usr/bin/memcat
/usr/bin/memcp
/usr/bin/memdump
/usr/bin/memerror
/usr/bin/memexist
/usr/bin/memflush
/usr/bin/memparse
/usr/bin/memping
/usr/bin/memrm
/usr/bin/memslap
/usr/bin/memstat
/usr/bin/memtouch

%files dev
%defattr(-,root,root,-)
/usr/include/libhashkit-1.0/algorithm.h
/usr/include/libhashkit-1.0/behavior.h
/usr/include/libhashkit-1.0/configure.h
/usr/include/libhashkit-1.0/digest.h
/usr/include/libhashkit-1.0/function.h
/usr/include/libhashkit-1.0/has.h
/usr/include/libhashkit-1.0/hashkit.h
/usr/include/libhashkit-1.0/hashkit.hpp
/usr/include/libhashkit-1.0/str_algorithm.h
/usr/include/libhashkit-1.0/strerror.h
/usr/include/libhashkit-1.0/string.h
/usr/include/libhashkit-1.0/types.h
/usr/include/libhashkit-1.0/visibility.h
/usr/include/libhashkit/hashkit.h
/usr/include/libmemcached-1.0/alloc.h
/usr/include/libmemcached-1.0/allocators.h
/usr/include/libmemcached-1.0/analyze.h
/usr/include/libmemcached-1.0/auto.h
/usr/include/libmemcached-1.0/basic_string.h
/usr/include/libmemcached-1.0/behavior.h
/usr/include/libmemcached-1.0/callback.h
/usr/include/libmemcached-1.0/callbacks.h
/usr/include/libmemcached-1.0/configure.h
/usr/include/libmemcached-1.0/defaults.h
/usr/include/libmemcached-1.0/delete.h
/usr/include/libmemcached-1.0/deprecated_types.h
/usr/include/libmemcached-1.0/dump.h
/usr/include/libmemcached-1.0/encoding_key.h
/usr/include/libmemcached-1.0/error.h
/usr/include/libmemcached-1.0/exception.hpp
/usr/include/libmemcached-1.0/exist.h
/usr/include/libmemcached-1.0/fetch.h
/usr/include/libmemcached-1.0/flush.h
/usr/include/libmemcached-1.0/flush_buffers.h
/usr/include/libmemcached-1.0/get.h
/usr/include/libmemcached-1.0/hash.h
/usr/include/libmemcached-1.0/limits.h
/usr/include/libmemcached-1.0/memcached.h
/usr/include/libmemcached-1.0/memcached.hpp
/usr/include/libmemcached-1.0/options.h
/usr/include/libmemcached-1.0/parse.h
/usr/include/libmemcached-1.0/platform.h
/usr/include/libmemcached-1.0/quit.h
/usr/include/libmemcached-1.0/result.h
/usr/include/libmemcached-1.0/return.h
/usr/include/libmemcached-1.0/sasl.h
/usr/include/libmemcached-1.0/server.h
/usr/include/libmemcached-1.0/server_list.h
/usr/include/libmemcached-1.0/stats.h
/usr/include/libmemcached-1.0/storage.h
/usr/include/libmemcached-1.0/strerror.h
/usr/include/libmemcached-1.0/struct/allocator.h
/usr/include/libmemcached-1.0/struct/analysis.h
/usr/include/libmemcached-1.0/struct/callback.h
/usr/include/libmemcached-1.0/struct/memcached.h
/usr/include/libmemcached-1.0/struct/result.h
/usr/include/libmemcached-1.0/struct/sasl.h
/usr/include/libmemcached-1.0/struct/server.h
/usr/include/libmemcached-1.0/struct/stat.h
/usr/include/libmemcached-1.0/struct/string.h
/usr/include/libmemcached-1.0/touch.h
/usr/include/libmemcached-1.0/triggers.h
/usr/include/libmemcached-1.0/types.h
/usr/include/libmemcached-1.0/types/behavior.h
/usr/include/libmemcached-1.0/types/callback.h
/usr/include/libmemcached-1.0/types/connection.h
/usr/include/libmemcached-1.0/types/hash.h
/usr/include/libmemcached-1.0/types/return.h
/usr/include/libmemcached-1.0/types/server_distribution.h
/usr/include/libmemcached-1.0/verbosity.h
/usr/include/libmemcached-1.0/version.h
/usr/include/libmemcached-1.0/visibility.h
/usr/include/libmemcached/memcached.h
/usr/include/libmemcached/memcached.hpp
/usr/include/libmemcached/util.h
/usr/include/libmemcachedutil-1.0/flush.h
/usr/include/libmemcachedutil-1.0/ostream.hpp
/usr/include/libmemcachedutil-1.0/pid.h
/usr/include/libmemcachedutil-1.0/ping.h
/usr/include/libmemcachedutil-1.0/pool.h
/usr/include/libmemcachedutil-1.0/util.h
/usr/include/libmemcachedutil-1.0/version.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc
/usr/share/aclocal/*.m4

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
